## connecting libraries

In [1]:
! pip install numpy
! pip install pandas
! pip install scikit-learn


Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [8]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from IPython.display import display


In [9]:
matrix = np.zeros([8,8])
matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1
display(matrix)

matrix = np.ones([8,8])
matrix[::2, ::2] = 0
matrix[1::2, 1::2] = 0
display(matrix)


array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arrange

In [11]:
a = np.zeros((5,5)) # Матрица 5x5
a += np.arange(5) # Значение в строках от 0 до 4
print(a)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Создать массив 3x3x3 со случайными значениями.

In [12]:
z = np.random.random((3,3,3))
print(z)


[[[0.16647622 0.8622429  0.06838123]
  [0.82680682 0.78012111 0.18182459]
  [0.88224566 0.76867549 0.27076286]]

 [[0.11807136 0.12663624 0.8840144 ]
  [0.51989834 0.81177293 0.63400779]
  [0.42056987 0.7291252  0.56054802]]

 [[0.37941278 0.73801882 0.86731754]
  [0.81820526 0.58632799 0.9105413 ]
  [0.71544746 0.04680331 0.3057364 ]]]


Создать матрицу с 0 внутри, и 1 на границах.

In [30]:
b = np.ones((5, 5))
b[1:-1, 1:-1] = 0
print(b)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Создайте массив и отсортируйте его по убыванию

In [31]:
arr = np.arange(1, 10)
print(np.sort(arr)[::-1])


[9 8 7 6 5 4 3 2 1]


Создайте матрицу, выведите ее форму, размер и размерность

In [32]:
a = 4
b = 4
A = np.zeros((a, b), int)

if a == b:
  form = 'квадратная'
else:
  form = 'прямоугольная'
print(A)
print('Форма матрицы:', form)
print('Размер:', a + b)
print('Размерность:', a * b)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Форма матрицы: квадратная
Размер: 8
Размерность: 16


Найти евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу

In [41]:
a = np.array((3, 0, 3))
b = np.array((3, 3, 3))

square = np.square(a - b)
sum_square = np.sum(square)

distance = np.sqrt(sum_square)
print(distance)


3.0


In [14]:
import pandas as pd


Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных (например, коллекцию фреймов данных можно найти здесь: https://github.com/akmand/datasets)

In [17]:
import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/kobe.csv'
dataframe = pd.read_csv(url)
dataframe.head(10)


vs  game quarter  time                                        description  \
0  ORL     1       1  9:47            Kobe Bryant makes 4-foot two point shot   
1  ORL     1       1  9:07                          Kobe Bryant misses jumper   
2  ORL     1       1  8:11                   Kobe Bryant misses 7-foot jumper   
3  ORL     1       1  7:41  Kobe Bryant makes 16-foot jumper (Derek Fisher...   
4  ORL     1       1  7:03                    Kobe Bryant makes driving layup   
5  ORL     1       1  6:01                          Kobe Bryant misses jumper   
6  ORL     1       1  4:07                  Kobe Bryant misses 12-foot jumper   
7  ORL     1       1  0:52                  Kobe Bryant misses 19-foot jumper   
8  ORL     1       1  0:00                           Kobe Bryant misses layup   
9  ORL     1       2  6:35                           Kobe Bryant makes jumper   

  basket  
0      H  
1      M  
2      M  
3      H  
4      H  
5      M  
6      M  
7      M  
8      M  
9      H

Проделайте с получившемся из предыдущего задания фреймом данных те же действия, что и в примерах 2.2.5-2.2.7

In [24]:
url = 'https://raw.githubusercontent.com/akmand/datasets/main/kobe.csv'
dataframe = pd.read_csv(url)
dataframe.head(2)
dataframe.tail(2)
dataframe.shape
dataframe.describe()
dataframe.iloc[1:4]
dataframe[dataframe['vs'] == 'ORL'].head(2)


vs  game quarter  time                              description basket
0  ORL     1       1  9:47  Kobe Bryant makes 4-foot two point shot      H
1  ORL     1       1  9:07                Kobe Bryant misses jumper      M

 Загрузить фрейм данных по ссылке: https://raw.githubusercontent.com/akmand/datasets/master/iris.csv. Необходимо выполнить нормализацию первого числового признака (sepal_length_cm) с использованием минимаксного преобразования, а второго (sepal_width_cm) с задействованием z-масштабирования

In [19]:
series = pd.read_csv("https://raw.githubusercontent.com/akmand/datasets/master/iris.csv")
series


sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0                5.1             3.5              1.4             0.2   
1                4.9             3.0              1.4             0.2   
2                4.7             3.2              1.3             0.2   
3                4.6             3.1              1.5             0.2   
4                5.0             3.6              1.4             0.2   
..               ...             ...              ...             ...   
145              6.7             3.0              5.2             2.3   
146              6.3             2.5              5.0             1.9   
147              6.5             3.0              5.2             2.0   
148              6.2             3.4              5.4             2.3   
149              5.9             3.0              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [23]:
normalized_series = series
normalized_series[['sepal_length_cm']] = preprocessing.MinMaxScaler().fit_transform(series[['sepal_length_cm']])
normalized_series[['sepal_width_cm']] = preprocessing.MaxAbsScaler().fit_transform(series[['sepal_width_cm']])


series


sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        0.795455              1.4             0.2   
1           0.166667        0.681818              1.4             0.2   
2           0.111111        0.727273              1.3             0.2   
3           0.083333        0.704545              1.5             0.2   
4           0.194444        0.818182              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667        0.681818              5.2             2.3   
146         0.555556        0.568182              5.0             1.9   
147         0.611111        0.681818              5.2             2.0   
148         0.527778        0.772727              5.4             2.3   
149         0.444444        0.681818              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]