In [27]:
import numpy as np

x = np.zeros((4,4),)
x[1::2,::2] = 1
x[0::2,1::2] = 1
print(x)


[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [28]:
a = np.zeros((5,5)) # Матрица 5x5
a += np.arange(5) # Значение в строках от 0 до 4
print(a)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [29]:
z = np.random.random((3,3,3))
print(z)


[[[0.09606024 0.4126839  0.79869703]
  [0.68347696 0.13895661 0.7123037 ]
  [0.72127307 0.58965775 0.09745654]]

 [[0.18133298 0.95509206 0.48977718]
  [0.4542227  0.36414771 0.0933646 ]
  [0.19993279 0.69813265 0.45047084]]

 [[0.72448014 0.22763346 0.39081902]
  [0.98396539 0.05413496 0.83086776]
  [0.61552009 0.18238853 0.16586925]]]


In [30]:
b = np.ones((5, 5))
b[1:-1, 1:-1] = 0
print(b)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [31]:
arr = np.arange(1, 10)
print(np.sort(arr)[::-1])


[9 8 7 6 5 4 3 2 1]


In [32]:
a = 4
b = 4
A = np.zeros((a, b), int)

if a == b:
  form = 'квадратная'
else:
  form = 'прямоугольная'
print(A)
print('Форма матрицы:', form)
print('Размер:', a + b)
print('Размерность:', a * b)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Форма матрицы: квадратная
Размер: 8
Размерность: 16


In [41]:
a = np.array((3, 0, 3))
b = np.array((3, 3, 3))

square = np.square(a - b)
sum_square = np.sum(square)

distance = np.sqrt(sum_square)
print(distance)


3.0


In [6]:
from venv import pandas as pd


ModuleNotFoundError: No module named 'pandas'